def MySimpleTest():
    my_list = LinkedList()
    my_list.insert(None, Node(14))
    my_list.add_in_tail(Node(10))
    my_list.delete(10, False)
    my_list.print_all_nodes()
    print('---------------------')
    my_list.add_in_tail(Node(16))
    my_list.add_in_tail(Node(16))
    my_list.add_in_tail(Node(15))
    my_list.add_in_tail(Node(16))
    my_list.add_in_tail(Node(16))
    my_list.add_in_tail(Node(16))
    my_list.delete(16, True)
    my_list.print_all_nodes()
    print(my_list.len())
    print(my_list.head.value)
    print(my_list.tail.value)
    print('---------------------')
    my_list.clean()
    my_list.print_all_nodes()
    print('---------------------')
    n0 = Node(76)
    my_list.add_in_tail(n0)
    my_list.add_in_tail(Node(55))
    my_list.add_in_tail(Node(12))
    my_list.add_in_tail(Node(128))
    my_list.add_in_tail(Node(55))
    outputList = my_list.find_all(55)
    for x in range(len(outputList)):
        print(outputList[x].value)
    print('---------------------')
    n1 = Node(13)
    my_list.add_in_tail(n1)
    my_list.insert(n1, Node(14))
    my_list.insert(n0, Node(78))
    my_list.print_all_nodes()
    print('---------------------')
    print(my_list.len())
    print(my_list.head.value)
    print(my_list.tail.value)

MySimpleTest()